/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class Main {
    // Kelas Node
    private static class Node {
        private char value;
        private Node next;

        public Node(char value) {
            this.value = value;
            this.next = null;
        }

        public void setNext(Node next) {
            this.next = next;
        }

        public Node getNext(){
            return this.next;
        }

        public char getValue(){
            return this.value;
        }
    }

    // Kelas LinkedList
    private static class LinkedList {
        private Node first;

        public LinkedList() {
            this.first = null;
        }

        public void add(char value) {
            Node newNode = new Node(value);  // Membuat node baru
            if (first == null) {             // Mengecek apakah node pertama ada atau tidak, jika tidak jalankan kode ini
                first = newNode;             // Jika tidak ada node, maka node pertama akan menjadi node baru
            } else {
                Node currentNode = first;    // Jika ada node pertama, currentnode dijadikan node pertama
                while (currentNode.getNext() != null) {     //perulangan akan berhenti ketika syarat terpenuhi, ketika alamat menuju node selanjutnya kosong (berada di akhir linkedlist)
                    currentNode = currentNode.getNext();    //getNext adalah method untuk mendapatkan alamat dari node selanjutnya
                }
                currentNode.setNext(newNode); // Menambahkan node baru di akhir
            }
        }

        public void printList() {
            Node currentNode = first;
            while (currentNode != null) {
                System.out.print(currentNode.getValue() + " ");
                currentNode = currentNode.getNext();
            }
            System.out.println();
        }
    }

    // Metode utama
    public static void main(String[] args) {
        LinkedList list = new LinkedList();

        list.add('a');
        list.add('b');
        list.add('c');

        list.printList(); // Ini akan mencetak isi dari linked list
    }
}
